# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kmeans.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckmeans.proto\"\n\n\x08\x41liveReq\"\n\n\x08\x41liveRes\"+\n\tCentroids\x12\x0e\n\x06x_cord\x18\x01 \x01(\x02\x12\x0e\n\x06y_cord\x18\x02 \x01(\x02\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"*\n\x04\x44\x61ta\x12\x0b\n\x03key\x18\x01 \x01(\x02\x12\x15\n\x05point\x18\x02 \x01(\x0b\x32\x06.Point\"\x8c\x01\n\x11MasterToMapperReq\x12\x13\n\x0bstart_index\x18\x01 \x01(\x05\x12\x11\n\tend_index\x18\x02 \x01(\x05\x12\x14\n\x0cmapper_index\x18\x03 \x01(\x05\x12\"\n\x0eprev_Centroids\x18\x04 \x03(\x0b\x32\n.Centroids\x12\x15\n\rreducer_count\x18\x05 \x01(\x05\"$\n\x11MasterToMapperRes\x12\x0f\n\x07success\x18\x01 \x01(\x05\"M\n\x12MasterToReducerReq\x12\x15\n\rstart_process\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\t\n\x01M\x18\x03 \x01(\x05\x12\t\n\x01R\x18\x04 \x01(\x05\"%\n\x12MasterToReducerRes\x12\x0f\n\x07success\x18\x01 \x01(\x05\"4\n\x12ReducerToMapperReq\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nNumMappers\x18\x02 \x01(\x05\":\n\x12ReducerToMapperRes\x12\x13\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x05.Data\x12\x0f\n\x07success\x18\x02 \x01(\x05\"%\n\x12MapperToReducerRes\x12\x0f\n\x07success\x18\x01 \x01(\x05\x32\xee\x01\n\x06Kmeans\x12:\n\x0eMasterToMapper\x12\x12.MasterToMapperReq\x1a\x12.MasterToMapperRes\"\x00\x12=\n\x0fMasterToReducer\x12\x13.MasterToReducerReq\x1a\x13.MasterToReducerRes\"\x00\x12=\n\x0fReducerToMapper\x12\x13.ReducerToMapperReq\x1a\x13.ReducerToMapperRes\"\x00\x12*\n\x10\x43heckMapperAlive\x12\t.AliveReq\x1a\t.AliveRes\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kmeans_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ALIVEREQ']._serialized_start=16
  _globals['_ALIVEREQ']._serialized_end=26
  _globals['_ALIVERES']._serialized_start=28
  _globals['_ALIVERES']._serialized_end=38
  _globals['_CENTROIDS']._serialized_start=40
  _globals['_CENTROIDS']._serialized_end=83
  _globals['_POINT']._serialized_start=85
  _globals['_POINT']._serialized_end=114
  _globals['_DATA']._serialized_start=116
  _globals['_DATA']._serialized_end=158
  _globals['_MASTERTOMAPPERREQ']._serialized_start=161
  _globals['_MASTERTOMAPPERREQ']._serialized_end=301
  _globals['_MASTERTOMAPPERRES']._serialized_start=303
  _globals['_MASTERTOMAPPERRES']._serialized_end=339
  _globals['_MASTERTOREDUCERREQ']._serialized_start=341
  _globals['_MASTERTOREDUCERREQ']._serialized_end=418
  _globals['_MASTERTOREDUCERRES']._serialized_start=420
  _globals['_MASTERTOREDUCERRES']._serialized_end=457
  _globals['_REDUCERTOMAPPERREQ']._serialized_start=459
  _globals['_REDUCERTOMAPPERREQ']._serialized_end=511
  _globals['_REDUCERTOMAPPERRES']._serialized_start=513
  _globals['_REDUCERTOMAPPERRES']._serialized_end=571
  _globals['_MAPPERTOREDUCERRES']._serialized_start=573
  _globals['_MAPPERTOREDUCERRES']._serialized_end=610
  _globals['_KMEANS']._serialized_start=613
  _globals['_KMEANS']._serialized_end=851
# @@protoc_insertion_point(module_scope)
